"""Experimental adaptive-routing interface contracts.

These helpers validate typed records and build privacy-bounded local input
observations. They do not select or execute a model.
"""

from .canonical import (
    CANONICAL_DECIMAL_V1_PATTERN,
    canonical_decimal_v1,
    canonical_json_v1,
    canonical_sha256_v1,
)
from .artifact_resolver import (
    ArtifactResolver,
    PinnedVerifiedArtifactSet,
    VerifiedArtifact,
    VerifiedArtifactSet,
)
from .activation import (
    EvidenceActivationOutcome,
    activate_qualification_evidence,
)
from .bundles import (
    AlgorithmBundleRegistry,
    AlgorithmBundleSpec,
    BundleLifecycleProjection,
    BundleLifecycleRecord,
    CODE_OWNED_RUNNER_IDS,
    SupportProfileProjection,
    SupportProfileRecord,
    SupportProfileSpec,
    build_fixed_class_mapping,
    map_fixed_class_outputs,
    map_text_prompt_outputs,
    project_bundle_lifecycle,
    project_support_profiles,
    validate_algorithm_bundle_registry,
    validate_algorithm_bundle_spec,
    validate_bundle_lifecycle_record,
    validate_support_profile_record,
    validate_support_profile_spec,
)
from .bundle_registry import (
    AlgorithmRunner,
    LoadedAlgorithmBundleRegistry,
    PinnedArtifactSet,
    PinnedInput,
    RunnerProbeResult,
    load_algorithm_bundle_registry,
)
from .control_records import (
    load_bounded_json,
    load_bounded_json_bytes,
    load_bounded_jsonl,
    load_bounded_jsonl_bytes,
)
from .contracts import (
    EnvironmentProfile,
    ImageJobSpec,
    QualificationWorkloadProfile,
    build_qualification_workload_profile,
    compute_environment_fingerprint,
    compute_workload_fingerprint,
    validate_environment_profile,
    validate_image_job_spec,
    validate_qualification_workload_profile,
)
from .evidence import (
    EvidenceActivationProjection,
    EvidenceActivationRecord,
    LocalArtifactInventory,
    QualificationReport,
    compute_artifact_state_fingerprint,
    compute_evidence_selection_key,
    load_evidence_activation_jsonl,
    load_evidence_activation_jsonl_bytes,
    project_evidence_activations,
    validate_evidence_activation_record,
    validate_local_artifact_inventory,
    validate_qualification_report,
)
from .environment import build_environment_profile
from .inventory import (
    DecodedInputInventory,
    DecodedInputObservation,
    build_decoded_input_inventory,
)
from .managed_output import (
    ManagedOutputCapabilities,
    ManagedOutputError,
    ManagedOutputLimits,
    ManagedOutputTransaction,
    RecoveryResult,
    recover_managed_output,
)
from .qualification import (
    QUALIFICATION_PROTOCOL_FINGERPRINT,
    QualificationError,
    QualificationEvaluator,
    nanoseconds_to_milliseconds,
    nearest_rank_nanoseconds,
    qualification_input_schedule,
    qualify_image_pipeline,
    qualification_report_has_code_owned_issuer,
)
from .selection import (
    CANDIDATE_REASON_CODES,
    ScreeningEligibilityObservation,
    SelectionDecision,
    SupportProfileEligibilityObservation,
    validate_screening_eligibility_observation,
    validate_selection_decision,
    validate_support_profile_eligibility_observation,
)

__all__ = [
    "AlgorithmBundleRegistry",
    "AlgorithmBundleSpec",
    "AlgorithmRunner",
    "ArtifactResolver",
    "BundleLifecycleProjection",
    "BundleLifecycleRecord",
    "CODE_OWNED_RUNNER_IDS",
    "CANONICAL_DECIMAL_V1_PATTERN",
    "CANDIDATE_REASON_CODES",
    "DecodedInputInventory",
    "DecodedInputObservation",
    "EnvironmentProfile",
    "EvidenceActivationProjection",
    "EvidenceActivationRecord",
    "EvidenceActivationOutcome",
    "ImageJobSpec",
    "LocalArtifactInventory",
    "LoadedAlgorithmBundleRegistry",
    "ManagedOutputCapabilities",
    "ManagedOutputError",
    "ManagedOutputLimits",
    "ManagedOutputTransaction",
    "PinnedArtifactSet",
    "PinnedVerifiedArtifactSet",
    "PinnedInput",
    "QualificationWorkloadProfile",
    "QualificationReport",
    "QualificationError",
    "QualificationEvaluator",
    "QUALIFICATION_PROTOCOL_FINGERPRINT",
    "RecoveryResult",
    "RunnerProbeResult",
    "ScreeningEligibilityObservation",
    "SelectionDecision",
    "SupportProfileProjection",
    "SupportProfileEligibilityObservation",
    "SupportProfileRecord",
    "SupportProfileSpec",
    "VerifiedArtifact",
    "VerifiedArtifactSet",
    "build_fixed_class_mapping",
    "build_decoded_input_inventory",
    "build_environment_profile",
    "build_qualification_workload_profile",
    "activate_qualification_evidence",
    "canonical_decimal_v1",
    "canonical_json_v1",
    "canonical_sha256_v1",
    "compute_environment_fingerprint",
    "compute_artifact_state_fingerprint",
    "compute_evidence_selection_key",
    "compute_workload_fingerprint",
    "load_bounded_json",
    "load_bounded_json_bytes",
    "load_bounded_jsonl",
    "load_bounded_jsonl_bytes",
    "load_algorithm_bundle_registry",
    "load_evidence_activation_jsonl",
    "load_evidence_activation_jsonl_bytes",
    "map_fixed_class_outputs",
    "map_text_prompt_outputs",
    "nanoseconds_to_milliseconds",
    "nearest_rank_nanoseconds",
    "project_bundle_lifecycle",
    "project_evidence_activations",
    "project_support_profiles",
    "qualification_input_schedule",
    "qualify_image_pipeline",
    "qualification_report_has_code_owned_issuer",
    "recover_managed_output",
    "validate_algorithm_bundle_registry",
    "validate_algorithm_bundle_spec",
    "validate_bundle_lifecycle_record",
    "validate_environment_profile",
    "validate_evidence_activation_record",
    "validate_image_job_spec",
    "validate_local_artifact_inventory",
    "validate_qualification_workload_profile",
    "validate_qualification_report",
    "validate_screening_eligibility_observation",
    "validate_selection_decision",
    "validate_support_profile_eligibility_observation",
    "validate_support_profile_record",
    "validate_support_profile_spec",
]
