"""Experimental adaptive-routing interface contracts.

These helpers validate typed records, build privacy-bounded local observations,
return a qualified selection or explicit abstention, and can explicitly execute
a pinned selected pipeline through the Experimental processing service.
"""

from .canonical import (
    CANONICAL_DECIMAL_V1_PATTERN,
    canonical_decimal_v1,
    canonical_json_v1,
    canonical_sha256_v1,
)
from .artifact_resolver import (
    ArtifactResolver,
    PinnedVerifiedArtifactSet,
    VerifiedArtifact,
    VerifiedArtifactSet,
)
from .activation import (
    EvidenceActivationOutcome,
    activate_qualification_evidence,
)
from .bundles import (
    AlgorithmBundleRegistry,
    AlgorithmBundleSpec,
    BundleLifecycleProjection,
    BundleLifecycleRecord,
    CODE_OWNED_RUNNER_IDS,
    SupportProfileProjection,
    SupportProfileRecord,
    SupportProfileSpec,
    build_fixed_class_mapping,
    map_fixed_class_outputs,
    map_text_prompt_outputs,
    project_bundle_lifecycle,
    project_support_profiles,
    validate_algorithm_bundle_registry,
    validate_algorithm_bundle_spec,
    validate_bundle_lifecycle_record,
    validate_support_profile_record,
    validate_support_profile_spec,
    validate_support_profile_snapshot,
)
from .bundle_registry import (
    AlgorithmRunner,
    LoadedAlgorithmBundleRegistry,
    PinnedArtifactSet,
    PinnedInput,
    RunnerProbeResult,
    load_algorithm_bundle_registry,
)
from .control_records import (
    load_bounded_json,
    load_bounded_json_bytes,
    load_bounded_jsonl,
    load_bounded_jsonl_bytes,
)
from .contracts import (
    EnvironmentProfile,
    ImageJobSpec,
    QualificationWorkloadProfile,
    build_qualification_workload_profile,
    compute_environment_fingerprint,
    compute_workload_fingerprint,
    validate_environment_profile,
    validate_image_job_spec,
    validate_qualification_workload_profile,
)
from .evidence import (
    EvidenceActivationProjection,
    EvidenceActivationRecord,
    LocalArtifactInventory,
    QualificationReport,
    compute_artifact_state_fingerprint,
    compute_evidence_selection_key,
    load_evidence_activation_jsonl,
    load_evidence_activation_jsonl_bytes,
    project_evidence_activations,
    validate_evidence_activation_record,
    validate_local_artifact_inventory,
    validate_qualification_report,
)
from .environment import build_environment_profile
from .inventory import (
    DecodedInputInventory,
    DecodedInputObservation,
    build_decoded_input_inventory,
)
from .managed_output import (
    ManagedOutputCapabilities,
    ManagedOutputError,
    ManagedOutputLimits,
    ManagedOutputTransaction,
    RecoveryResult,
    recover_managed_output,
    validate_managed_output_destination,
)
from .isolation import (
    IsolatedRunnerCapability,
    IsolatedRunnerService,
)
from .lifecycle import (
    LifecycleUpdateOutcome,
    update_image_pipeline_lifecycle,
)
from .promotion import PromotionOutcome, promote_image_pipeline
from .processing import (
    ProcessingError,
    process_images,
)
from .qualification import (
    QUALIFICATION_PROTOCOL_FINGERPRINT,
    QualificationError,
    QualificationEvaluator,
    nanoseconds_to_milliseconds,
    nearest_rank_nanoseconds,
    qualification_input_schedule,
    qualify_image_pipeline,
    qualification_report_has_code_owned_issuer,
)
from .recommendation import RecommendationError, recommend_image_pipeline
from .screening import (
    CandidateScreeningProjection,
    CandidateScreeningRecord,
    MAX_SCREENING_RECORDS,
    MAX_SCREENING_STREAM_BYTES,
    build_screening_eligibility_observation,
    compute_candidate_screening_stream_key,
    load_candidate_screening_jsonl_bytes,
    project_candidate_screening_records,
    validate_candidate_screening_record,
)
from .selection import (
    CANDIDATE_REASON_CODES,
    ScreeningEligibilityObservation,
    SelectionDecision,
    SupportProfileEligibilityObservation,
    validate_screening_eligibility_observation,
    validate_selection_decision,
    validate_support_profile_eligibility_observation,
)
from .selector import (
    EvidenceEligibilityObservation,
    IsolationCapabilityObservation,
    compute_advertised_gates_digest,
    evidence_eligibility_from_projection,
    select_qualified_pipeline,
)
from .support_profiles import (
    MAX_SUPPORT_PROFILE_STREAM_BYTES,
    SupportProfileReviewOutcome,
    build_support_profile_eligibility_observation,
    load_support_profile_jsonl_bytes,
    review_image_pipeline_support_profiles,
)

__all__ = [
    "AlgorithmBundleRegistry",
    "AlgorithmBundleSpec",
    "AlgorithmRunner",
    "ArtifactResolver",
    "BundleLifecycleProjection",
    "BundleLifecycleRecord",
    "CODE_OWNED_RUNNER_IDS",
    "CANONICAL_DECIMAL_V1_PATTERN",
    "CANDIDATE_REASON_CODES",
    "CandidateScreeningProjection",
    "CandidateScreeningRecord",
    "DecodedInputInventory",
    "DecodedInputObservation",
    "EnvironmentProfile",
    "EvidenceActivationProjection",
    "EvidenceActivationRecord",
    "EvidenceActivationOutcome",
    "EvidenceEligibilityObservation",
    "ImageJobSpec",
    "IsolationCapabilityObservation",
    "IsolatedRunnerCapability",
    "IsolatedRunnerService",
    "LocalArtifactInventory",
    "LifecycleUpdateOutcome",
    "LoadedAlgorithmBundleRegistry",
    "ManagedOutputCapabilities",
    "ManagedOutputError",
    "ManagedOutputLimits",
    "ManagedOutputTransaction",
    "MAX_SCREENING_RECORDS",
    "MAX_SCREENING_STREAM_BYTES",
    "MAX_SUPPORT_PROFILE_STREAM_BYTES",
    "PinnedArtifactSet",
    "PinnedVerifiedArtifactSet",
    "PinnedInput",
    "ProcessingError",
    "PromotionOutcome",
    "QualificationWorkloadProfile",
    "QualificationReport",
    "QualificationError",
    "QualificationEvaluator",
    "QUALIFICATION_PROTOCOL_FINGERPRINT",
    "RecommendationError",
    "RecoveryResult",
    "RunnerProbeResult",
    "ScreeningEligibilityObservation",
    "SelectionDecision",
    "SupportProfileProjection",
    "SupportProfileReviewOutcome",
    "SupportProfileEligibilityObservation",
    "SupportProfileRecord",
    "SupportProfileSpec",
    "VerifiedArtifact",
    "VerifiedArtifactSet",
    "build_fixed_class_mapping",
    "build_screening_eligibility_observation",
    "build_support_profile_eligibility_observation",
    "build_decoded_input_inventory",
    "build_environment_profile",
    "build_qualification_workload_profile",
    "activate_qualification_evidence",
    "canonical_decimal_v1",
    "canonical_json_v1",
    "canonical_sha256_v1",
    "compute_environment_fingerprint",
    "compute_artifact_state_fingerprint",
    "compute_advertised_gates_digest",
    "compute_evidence_selection_key",
    "compute_candidate_screening_stream_key",
    "compute_workload_fingerprint",
    "evidence_eligibility_from_projection",
    "load_bounded_json",
    "load_bounded_json_bytes",
    "load_bounded_jsonl",
    "load_bounded_jsonl_bytes",
    "load_algorithm_bundle_registry",
    "load_evidence_activation_jsonl",
    "load_evidence_activation_jsonl_bytes",
    "load_candidate_screening_jsonl_bytes",
    "load_support_profile_jsonl_bytes",
    "map_fixed_class_outputs",
    "map_text_prompt_outputs",
    "nanoseconds_to_milliseconds",
    "nearest_rank_nanoseconds",
    "project_bundle_lifecycle",
    "project_candidate_screening_records",
    "project_evidence_activations",
    "project_support_profiles",
    "review_image_pipeline_support_profiles",
    "process_images",
    "promote_image_pipeline",
    "qualification_input_schedule",
    "qualify_image_pipeline",
    "qualification_report_has_code_owned_issuer",
    "recover_managed_output",
    "recommend_image_pipeline",
    "select_qualified_pipeline",
    "validate_algorithm_bundle_registry",
    "validate_algorithm_bundle_spec",
    "validate_bundle_lifecycle_record",
    "validate_candidate_screening_record",
    "validate_environment_profile",
    "validate_evidence_activation_record",
    "validate_image_job_spec",
    "validate_local_artifact_inventory",
    "validate_managed_output_destination",
    "validate_qualification_workload_profile",
    "validate_qualification_report",
    "validate_screening_eligibility_observation",
    "validate_selection_decision",
    "validate_support_profile_eligibility_observation",
    "validate_support_profile_record",
    "validate_support_profile_spec",
    "validate_support_profile_snapshot",
    "update_image_pipeline_lifecycle",
]
