"""Contract helpers for external dataset/model integrations."""

from .synthgen import (
    SYNTHGEN_REQUIRED_FIELDS,
    SynthGenValidationResult,
    normalize_synthgen_sample,
    validate_synthgen_sample,
)
from .ocr import (
    OCRBundleInterface,
    OCRContractError,
    OCRResult,
    map_ocr_runner_result,
    privacy_safe_ocr_summary,
    validate_ocr_bundle_interface,
    validate_ocr_input_media,
    validate_ocr_result,
)
from .tracking import (
    JS_SAFE_TRACK_ID_MAX,
    MAX_ACTIVE_TRACKS,
    MAX_JOB_ROW_STATE_BUDGET,
    MAX_SESSION_UNIQUE_TRACKS,
    MAX_TRACKING_MASK_ARTIFACTS,
    MAX_TRACKING_OUTPUT_FILES,
    MAX_TRACKING_ROWS_PER_FRAME,
    TrackingContractError,
    TrackingOutputInterface,
    TrackingStateMachine,
    TrackingValidationSummary,
    validate_tracking_output_interface,
    validate_tracking_output_artifacts,
    validate_tracking_output_provenance,
    validate_tracking_output_record,
    validate_tracking_output_streams,
)

__all__ = [
    "SYNTHGEN_REQUIRED_FIELDS",
    "SynthGenValidationResult",
    "normalize_synthgen_sample",
    "validate_synthgen_sample",
    "OCRBundleInterface",
    "OCRContractError",
    "OCRResult",
    "map_ocr_runner_result",
    "privacy_safe_ocr_summary",
    "validate_ocr_bundle_interface",
    "validate_ocr_input_media",
    "validate_ocr_result",
    "JS_SAFE_TRACK_ID_MAX",
    "MAX_ACTIVE_TRACKS",
    "MAX_JOB_ROW_STATE_BUDGET",
    "MAX_SESSION_UNIQUE_TRACKS",
    "MAX_TRACKING_MASK_ARTIFACTS",
    "MAX_TRACKING_OUTPUT_FILES",
    "MAX_TRACKING_ROWS_PER_FRAME",
    "TrackingContractError",
    "TrackingOutputInterface",
    "TrackingStateMachine",
    "TrackingValidationSummary",
    "validate_tracking_output_interface",
    "validate_tracking_output_artifacts",
    "validate_tracking_output_provenance",
    "validate_tracking_output_record",
    "validate_tracking_output_streams",
]
