name: ClusterFuzzLite batch fuzzing

on:
  workflow_dispatch:

permissions: read-all

jobs:
  batch-fuzzing:
    name: Batch fuzzing (${{ matrix.sanitizer }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 900
          mode: batch
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true

      - name: Upload fuzzing SARIF
        if: ${{ always() && hashFiles('fuzzing-sarif/results.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: fuzzing-sarif/results.sarif
